import { NextResponse, type NextRequest } from 'next/server';
import { createHash } from 'node:crypto';
import JSZip from 'jszip';
import { createSupabaseServer } from '@/lib/supabase/server';
import { requireRole } from '@/lib/auth';

export const runtime = 'nodejs';
export const dynamic = 'force-dynamic';

export async function GET(
  _req: NextRequest,
  { params }: { params: { contractId: string } },
): Promise<NextResponse> {
  await requireRole(['master_admin', 'auditor', 'cfo']);

  const supabase = await createSupabaseServer();
  const { data: contract } = await supabase
    .from('contracts')
    .select(`id, contract_type, status, document_storage_path, document_sha256,
             fully_signed_pdf_path, fully_signed_pdf_sha256, fully_signed_at,
             required_signatories, template_id, template_version,
             application_id, loan_id, created_at`)
    .eq('id', params.contractId)
    .maybeSingle();

  if (!contract) return NextResponse.json({ error: 'not found' }, { status: 404 });

  const [{ data: sigs }, { data: events }] = await Promise.all([
    supabase
      .from('contract_signatures')
      .select('*')
      .eq('contract_id', contract.id)
      .order('signed_at', { ascending: true }),
    supabase
      .from('contract_audit_events')
      .select('*')
      .eq('contract_id', contract.id)
      .order('occurred_at', { ascending: true }),
  ]);

  const zip = new JSZip();

  // Sealed PDF (or original if not yet sealed)
  let sealedBytes: Uint8Array | null = null;
  let sealedFilename = 'document.pdf';
  if (contract.fully_signed_pdf_path) {
    const { data: blob } = await supabase.storage
      .from('contracts')
      .download(contract.fully_signed_pdf_path);
    if (blob) {
      sealedBytes = new Uint8Array(await blob.arrayBuffer());
      sealedFilename = 'sealed.pdf';
    }
  } else if (contract.document_storage_path) {
    const { data: blob } = await supabase.storage
      .from('contracts')
      .download(contract.document_storage_path);
    if (blob) {
      sealedBytes = new Uint8Array(await blob.arrayBuffer());
      sealedFilename = 'document-unsealed.pdf';
    }
  }
  if (sealedBytes) zip.file(sealedFilename, sealedBytes);

  // Evidence JSON
  const evidence = {
    contract: contract,
    signatures: sigs ?? [],
    audit_events: events ?? [],
    exported_at: new Date().toISOString(),
    exported_by_role: 'auditor_or_admin',
  };
  const evidenceJson = JSON.stringify(evidence, null, 2);
  zip.file('evidence.json', evidenceJson);

  // README
  const readme = `# Contract evidence bundle
Contract: ${contract.id}
Type:     ${contract.contract_type}
Status:   ${contract.status}
Exported: ${new Date().toISOString()}

## Contents

* ${sealedFilename}  — the contract PDF (sealed or pending)
* evidence.json     — every contract_signatures + contract_audit_events row
* manifest.json     — file path + SHA-256 for every file in this archive

## How to verify

1. Recompute SHA-256 of ${sealedFilename}:
   shasum -a 256 ${sealedFilename}
2. Compare against contract.fully_signed_pdf_sha256 inside evidence.json
   (or contract.document_sha256 if unsealed).
3. For PAdES Baseline-T signatures, open ${sealedFilename} in Adobe Acrobat
   or any standard PDF reader — it will validate the embedded X.509
   signature against Richmond Finance's published public key at:
   https://www.richmond-afri.com/legal/signing-cert
4. Cross-check every signatory's envelope_sha256 in evidence.json against
   the value in their corresponding signed event in audit_events.

Generated by Richmond Finance Employee Payroll Loan Portal.
`;
  zip.file('README.md', readme);

  // Manifest
  const sha256Of = (b: Uint8Array | string): string =>
    createHash('sha256').update(typeof b === 'string' ? b : Buffer.from(b)).digest('hex');
  const manifest = {
    contract_id: contract.id,
    generated_at: new Date().toISOString(),
    files: [
      sealedBytes
        ? { path: sealedFilename, sha256: sha256Of(sealedBytes), bytes: sealedBytes.length }
        : null,
      { path: 'evidence.json', sha256: sha256Of(evidenceJson), bytes: evidenceJson.length },
      { path: 'README.md', sha256: sha256Of(readme), bytes: readme.length },
    ].filter(Boolean),
  };
  zip.file('manifest.json', JSON.stringify(manifest, null, 2));

  const out = await zip.generateAsync({ type: 'uint8array' });
  return new NextResponse(out as unknown as BodyInit, {
    headers: {
      'Content-Type': 'application/zip',
      'Content-Disposition': `attachment; filename="contract-${contract.id}-evidence.zip"`,
    },
  });
}
